import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const portfoliosStorePath = path.resolve(__dirname, 'portfolios_store.json');

const seedPortfolios = [
  {
    id: 1,
    slug: "wepose",
    title: "Wepose Visa Assistant",
    category: "web",
    category_label: "Website & Web App",
    image_url: "/images/wepose_web.png",
    video_url: "",
    short_desc: "Sistem pengajuan visa terintegrasi AI Chatbot untuk mempermudah birokrasi aplikasi perjalanan internasional.",
    client: "Wepose Agensi Layanan Visa",
    year: "2025",
    tags: ["Laravel 11", "Svelte Kit", "Mastra", "n8n", "Go"],
    challenge: "Tingkat kerumitan regulasi 35+ negara dan tingginya volume tiket pertanyaan manual seputar dokumen visa.",
    solution: "Membangun dashboard pelacakan terpusat dan chatbot asisten AI interaktif dengan n8n & Mastra.",
    results: "Otomatisasi 24/7 customer care, penanganan 35+ negara secara dinamis, dan peningkatan efisiensi operasional sebesar 50%.",
    demo_url: "/demo/wepose",
    live_url: "https://wepose.travel",
    project_importance: "Pengajuan visa internasional sering kali menjadi proses yang menakutkan, membingungkan, dan rawan kesalahan bagi banyak pelancong. Berkas yang tidak lengkap atau informasi yang tertinggal dapat berujung pada penolakan visa yang merugikan secara waktu dan finansial. Melalui proyek Wepose, kami membuktikan bagaimana perpaduan antara desain antarmuka yang intuitif dan kecerdasan buatan (AI Chatbot) dapat mengubah birokrasi pengajuan visa yang rumit menjadi proses digital yang effortless, transparan, dan terstruktur.",
    client_info: "Wepose, agensi layanan pengajuan visa yang menangani proses aplikasi ke lebih dari 35 negara tujuan dengan pengalaman bertahun-tahun.",
    stat_1_val: "24/7",
    stat_1_label: "Layanan Pelanggan (AI)",
    stat_1_desc: "Integrasi AI Chatbot memastikan setiap calon pelancong mendapatkan jawaban instan mengenai syarat visa kapan pun tanpa batasan jam kerja.",
    stat_2_val: "35+",
    stat_2_label: "Manajemen Destinasi Dinamis",
    stat_2_desc: "Platform mampu mengelola regulasi, biaya, dan persyaratan dokumen untuk lebih dari 35 negara tujuan yang dapat diperbarui secara mandiri melalui CMS.",
    stat_3_val: "50%",
    stat_3_label: "Efisiensi Tim Operasional",
    stat_3_desc: "Pengurangan beban tiket pertanyaan masuk secara manual berkat sistem website yang informatif dan fitur pelacakan status (tracking) mandiri oleh pengguna.",
    challenge_detailed: "Tingtingya volume pertanyaan berulang dari pelanggan mengenai persyaratan visa, status aplikasi, dan biaya untuk berbagai negara. Proses pengumpulan dan verifikasi dokumen yang dilakukan secara manual melalui aplikasi pesan instan sering menyebabkan dokumen terselip, lambatnya respons layanan pelanggan, dan pengalaman pengguna yang kurang profesional. Regulasi Visa yang Dinamis: Setiap kedutaan memiliki syarat dokumen dan harga yang berbeda-beda dan bisa berubah sewaktu-waktu. Sistem harus sangat fleksibel agar admin dapat mengubah requirement ini tanpa harus merombak kode sumber.",
    solution_detailed: "Kodeflow mendesain Wepose sebagai platform SaaS-like yang memadukan automasi cerdas dengan manajemen data terstruktur: 1. Conversational Interface Pipeline: Menghubungkan frontend dengan layanan pemrosesan bahasa alami (NLP) untuk Chatbot, memungkinkan bot memahami konteks pertanyaan pengguna seputar visa dan memberikan jawaban yang relevan dari knowledge base Wepose. 2. Secure Document Flow: Membangun arsitektur unggah dokumen (upload architecture) yang menggunakan cloud storage terenkripsi. Dokumen hanya dapat diakses oleh pelanggan yang bersangkutan dan admin Wepose yang memiliki otorisasi. 3. Dynamic Content Management: Mengembangkan CMS headless atau arsitektur terdekopel di mana tim internal dapat dengan mudah menambah negara tujuan baru, mengkustomisasi form persyaratan visa, dan menyesuaikan harga secara mandiri.",
    testimonial_text: "Proses development yg sangat cepat dan transparant sehingga kami dapat dengan mudah menyampaikan apa yang kami inginkan.",
    testimonial_author: "IT Leader Wepose",
    media: [{ type: "image", url: "/images/wepose_web.png" }]
  },
  {
    id: 2,
    slug: "lppm-portal",
    title: "LPPM Portal Penelitian",
    category: "web",
    category_label: "Website & Web App",
    image_url: "/images/lppm_dashboard.png",
    video_url: "",
    short_desc: "Portal manajemen pengajuan penelitian dan pengabdian masyarakat terintegrasi bagi institusi pendidikan tinggi.",
    client: "Universitas Berdikari",
    year: "2025",
    tags: ["React", "TypeScript", "Node.js", "Express", "PostgreSQL"],
    challenge: "Pengajuan proposal dan laporan dana penelitian dilakukan manual lewat berkas cetak yang rentan hilang.",
    solution: "Sistem informasi terintegrasi untuk pengumpulan, review reviewer eksternal, laporan kemajuan, dan statistik penyerapan dana.",
    results: "Memangkas birokrasi hingga 70%, 500+ proposal diproses secara simultan, dan transparansi dana hibah penelitian 100%.",
    demo_url: "/demo/lppm-portal",
    live_url: "",
    project_importance: "Pengelolaan kegiatan akademik di luar perkuliahan (penelitian dan pengabdian masyarakat) sering terhambat proses birokrasi manual. Berkas proposal riset berlembar-lembar harus ditandatangani basah, dinilai oleh reviewer secara manual lewat berkas kertas, dan laporan kemajuan sering terlambat diserahkan. Portal LPPM memfasilitasi keseluruhan siklus riset ini secara digital sehingga proses transfer dana hibah menjadi lebih akuntabel.",
    client_info: "Lembaga Penelitian dan Pengabdian Masyarakat (LPPM) adalah unit universitas yang mengelola hibah penelitian internal dan eksternal.",
    stat_1_val: "70%",
    stat_1_label: "Pemangkasan Birokrasi",
    stat_1_desc: "Alur kerja persetujuan proposal dari tingkat kaprodi, dekan, hingga LPPM kini sepenuhnya digital tanpa dokumen fisik.",
    stat_2_val: "500+",
    stat_2_label: "Proposal Terproses",
    stat_2_desc: "Sistem mampu menangani pengumpulan dan penugasan review proposal riset secara online untuk ratusan dosen peneliti secara serentak.",
    stat_3_val: "100%",
    stat_3_label: "Transparansi Anggaran Riset",
    stat_3_desc: "Dosen dan manajemen universitas dapat melacak secara tepat penyerapan anggaran dana hibah di setiap tahapan riset.",
    challenge_detailed: "Setiap tahun, dosen peneliti dihadapkan pada tumpukan berkas pengajuan manual. Reviewer kesulitan memberikan penilaian objektif secara terstruktur. LPPM juga kesulitan melacak progress luaran penelitian (seperti publikasi jurnal atau paten) karena tidak ada database terpadu.",
    solution_detailed: "Mengembangkan portal dengan sistem multi-role (Dosen, Reviewer, Kaprodi, Admin LPPM) yang memfasilitasi pengunggahan proposal, lembar penilaian reviewer (scoring sheet), tracking logbook harian riset, hingga pengunggahan bukti luaran ilmiah secara mandiri.",
    testimonial_text: "Portal LPPM ini memudahkan kami melacak luaran penelitian dosen secara real-time untuk kebutuhan akreditasi institusi.",
    testimonial_author: "Ketua LPPM Universitas Berdikari",
    media: [{ type: "image", url: "/images/lppm_dashboard.png" }]
  },
  {
    id: 3,
    slug: "erp-aethera",
    title: "Aethera Enterprise ERP",
    category: "web",
    category_label: "Website & Web App",
    image_url: "/images/erp_dashboard.png",
    video_url: "",
    short_desc: "Dashboard ERP kustom untuk otomatisasi keuangan, SDM, dan rantai pasokan korporasi.",
    client: "PT Aethera Manufaktur",
    year: "2025",
    tags: ["React", "TypeScript", "Node.js", "PostgreSQL", "Chart.js"],
    challenge: "Mengintegrasikan data multi-cabang yang sebelumnya tersebar secara manual di Excel, menyebabkan keterlambatan sinkronisasi data keuangan hingga 4 hari.",
    solution: "Menangani sinkronisasi data real-time kurang dari 2 detik dan visualisasi chart interaktif untuk pengambilan keputusan instan.",
    results: "Meningkatkan akurasi laporan keuangan hingga 99.8%, menghemat 120+ jam kerja administratif per bulan, dan mempercepat rekonsiliasi bulanan dari 4 hari menjadi 15 menit.",
    demo_url: "/demo/erp-aethera",
    live_url: "https://aethera-demo.berdikari.co",
    project_importance: "Dalam industri manufaktur skala menengah ke atas, sinkronisasi data antar cabang sangat krusial. Tanpa sistem yang terintegrasi, inventarisasi gudang, manajemen HRD, dan data penjualan mengalami lag yang berdampak buruk pada proses pengadaan bahan baku.",
    client_info: "PT Aethera Manufaktur adalah perusahaan perakitan suku cadang otomotif terkemuka dengan 3 cabang pabrik di Jawa Barat.",
    stat_1_val: "2dtk",
    stat_1_label: "Sinkronisasi Data",
    stat_1_desc: "Data operasional dari 3 cabang terintegrasi secara real-time di bawah 2 detik untuk menghindari duplikasi data.",
    stat_2_val: "120+",
    stat_2_label: "Jam Kerja Dihemat",
    stat_2_desc: "Otomatisasi proses input data rekonsiliasi inventaris dan penggajian karyawan memangkas lembur staf administrasi.",
    stat_3_val: "15mnt",
    stat_3_label: "Rekonsiliasi Bulanan",
    stat_3_desc: "Menyusun laporan bulanan konsolidasi kini selesai dalam hitungan menit dari sebelumnya membutuhkan waktu 4 hari kerja.",
    challenge_detailed: "Data inventori di gudang seringkali tidak sinkron dengan laporan penjualan, menyebabkan tim produksi memproduksi suku cadang yang stoknya masih melimpah sementara stok yang kritis justru kosong.",
    solution_detailed: "Membangun modul Enterprise Resource Planning (ERP) berbasis web terintegrasi dengan modul Finance, Supply Chain, and HR. Dilengkapi dengan rest API berkinerja tinggi serta optimasi index database PostgreSQL.",
    testimonial_text: "ERP ini membantu kami menyinkronkan rantai produksi kami secara efisien. Keterlambatan pengadaan material berkurang drastis.",
    testimonial_author: "Direktur Operasional Aethera",
    media: [{ type: "image", url: "/images/erp_dashboard.png" }]
  },
  {
    id: 4,
    slug: "medplus-health",
    title: "MedPlus Health Solution",
    category: "mobile",
    category_label: "Mobile Application",
    image_url: "/images/medical_app.png",
    video_url: "",
    short_desc: "Aplikasi konsultasi dokter online, rekam medis digital, dan pemesanan obat langsung.",
    client: "Klinik MedPlus Utama",
    year: "2025",
    tags: ["Flutter", "Firebase", "Node.js", "Google Maps API"],
    challenge: "Pasien harus mengantre hingga 2 jam untuk konsultasi rutin dan kesulitan melacak riwayat resep obat secara digital.",
    solution: "Mengembangkan aplikasi mobile Android & iOS dengan fitur telekonsultasi video terintegrasi, pemesanan obat berbasis lokasi, dan e-medical record terenkripsi.",
    results: "Mengurangi waktu tunggu pasien sebesar 82%, melayani 5.000+ telekonsultasi aktif di bulan pertama, dan meningkatkan retensi pasien klinik sebesar 45%.",
    demo_url: "/demo/medplus-health",
    live_url: "",
    project_importance: "Pelayanan kesehatan tradisional sering terhambat oleh antrean fisik yang padat dan resep obat kertas yang gampang hilang. Pasien membutuhkan alternatif layanan jarak jauh (telemedicine) yang andal dan mudah diakses langsung lewat ponsel pintar.",
    client_info: "Klinik MedPlus Utama merupakan jaringan klinik kesehatan keluarga dengan puluhan dokter spesialis berlisensi.",
    stat_1_val: "82%",
    stat_1_label: "Pengurangan Waktu Tunggu",
    stat_1_desc: "Daftar konsultasi via mobile memangkas waktu tunggu di ruang tunggu klinik secara dramatis.",
    stat_2_val: "5.000+",
    stat_2_label: "Pasien Terlayani",
    stat_2_desc: "Bulan pertama peluncuran mencatat ribuan telekonsultasi sukses melalui sambungan video terenkripsi.",
    stat_3_val: "45%",
    stat_3_label: "Retensi Pasien",
    stat_3_desc: "Pasien lebih setia kembali berobat berkat riwayat medis digital dan notifikasi resep otomatis di ponsel mereka.",
    challenge_detailed: "Kepadatan pasien di klinik fisik di jam-jam sibuk menimbulkan risiko penularan penyakit di ruang tunggu dan kelelahan staf medis.",
    solution_detailed: "Mengembangkan aplikasi mobile Flutter dengan integrasi layanan video call WebRTC, database rekam medis terenkripsi berbasis Firebase, dan tracking pengiriman obat ojek online.",
    testimonial_text: "Sistem telekonsultasi MedPlus membantu kami menjangkau pasien di daerah terpencil dengan sangat baik dan profesional.",
    testimonial_author: "Kepala Klinik MedPlus",
    media: [{ type: "image", url: "/images/medical_app.png" }]
  },
  {
    id: 5,
    slug: "solaria-ecommerce",
    title: "Solaria Premium E-Commerce",
    category: "web",
    category_label: "Website & Web App",
    image_url: "/images/ecommerce_web.png",
    video_url: "",
    short_desc: "Platform belanja online dengan navigasi modern, checkout kilat, dan payment gateway.",
    client: "Solaria Retail Group",
    year: "2024",
    tags: ["Next.js", "TailwindCSS", "Stripe", "GraphQL", "Shopify API"],
    challenge: "Tingkat drop-off (keranjang belanja ditinggalkan) mencapai 68% karena proses pengisian formulir checkout yang berbelit-belit.",
    solution: "Mendesain ulang user flow website dan mengimplementasikan fitur checkout satu klik dengan integrasi payment gateway otomatis yang menurunkan tingkat drop-off menjadi 22%.",
    results: "Menurunkan tingkat keranjang belanja diabaikan sebesar 46%, meningkatkan rata-rata nilai transaksi (AOV) sebesar 18%, dan mendongkrak penjualan online sebesar 32%.",
    demo_url: "/demo/solaria-ecommerce",
    live_url: "https://solaria-ecommerce.com",
    project_importance: "Toko ritel fisik Solaria membutuhkan ekspansi digital berskala besar untuk menangkap pasar Gen-Z. Website lama mereka lambat dan memiliki alur belanja yang memusingkan bagi pengguna ponsel.",
    client_info: "Solaria Retail Group adalah brand pakaian gaya hidup kontemporer dengan 50+ gerai di pusat perbelanjaan.",
    stat_1_val: "46%",
    stat_1_label: "Pengurangan Drop-off",
    stat_1_desc: "Checkout ringkas menurunkan tingkat keranjang belanja yang terbengkalai secara drastis.",
    stat_2_val: "18%",
    stat_2_label: "Kenaikan Nilai Transaksi",
    stat_2_desc: "Fitur upsell otomatis berdasarkan rekomendasi produktif AI di keranjang mendorong pembelian tambahan.",
    stat_3_val: "32%",
    stat_3_label: "Kenaikan Penjualan Online",
    stat_3_desc: "Kecepatan loading website berbasis server-side rendering Next.js melipatgandakan konversi pengunjung.",
    challenge_detailed: "Platform e-commerce lama sering lambat memproses gambar resolusi tinggi produk pakaian, berakibat pada tingginya bounce rate pengunjung di bawah 5 detik.",
    solution_detailed: "Mendesain dan mendeploy web e-commerce Next.js headless menggunakan Shopify API untuk manajemen inventori serta Stripe untuk pembayaran internasional terenkripsi.",
    testimonial_text: "Sistem e-commerce baru ini terasa sangat cepat di mobile. Konversi penjualan digital kami melonjak tajam.",
    testimonial_author: "VP E-Commerce Solaria",
    media: [{ type: "image", url: "/images/ecommerce_web.png" }]
  },
  {
    id: 6,
    slug: "velo-wallet",
    title: "Velo E-Wallet & Crypto",
    category: "mobile",
    category_label: "Mobile Application",
    image_url: "/images/ewallet_app.png",
    video_url: "",
    short_desc: "Aplikasi dompet digital multifungsi untuk transfer, pembayaran biller, dan jual-beli crypto.",
    client: "Velo Finance Ltd.",
    year: "2025",
    tags: ["React Native", "Web3.js", "NestJS", "Redis", "FaceID SDK"],
    challenge: "Memerlukan otentikasi transaksi super aman yang tetap terasa cepat dan tanpa lag di ponsel berspesifikasi rendah.",
    solution: "Membuat aplikasi e-wallet ultra-ringan dengan otentikasi biometrik lokal yang diamankan enkripsi AES-256 dan sinkronisasi blockchain asinkron.",
    results: "Mencapai 200.000+ pengguna aktif bulanan dalam 90 hari pertama, dengan tingkat keberhasilan transaksi 99,99% dan rating 4.8 di Play Store.",
    demo_url: "/demo/velo-wallet",
    live_url: "",
    project_importance: "Aplikasi keuangan terdesentralisasi (Web3) seringkali dinilai terlalu rumit untuk pengguna awam. Penggabungan fitur dompet konvensional (fiat) dan mata uang kripto dalam satu UI yang sederhana adalah tantangan produk ini.",
    client_info: "Velo Finance Ltd. adalah startup fintech berlisensi yang fokus pada inklusi keuangan digital modern.",
    stat_1_val: "200K+",
    stat_1_label: "Pengguna Aktif",
    stat_1_desc: "Mendapatkan antusiasme tinggi berkat kemudahan transaksi crypto tanpa pemahaman teknis blockchain yang rumit.",
    stat_2_val: "99,99%",
    stat_2_label: "Keberhasilan Transaksi",
    stat_2_desc: "Optimasi caching backend Redis menjamin tidak ada transaksi ganda atau kegagalan transfer.",
    stat_3_val: "4.8",
    stat_3_label: "Rating Play Store",
    stat_3_desc: "Ulasan positif memuji kemudahan otentikasi sidik jari/FaceID dan kelancaran UI aplikasi.",
    challenge_detailed: "Waktu sinkronisasi data saldo blockchain seringkali lambat di jaringan internet seluler yang kurang stabil di daerah rural.",
    solution_detailed: "Membangun aplikasi mobile cross-platform dengan React Native, modul enkripsi native biometrik FaceID/Keychain, serta microservices NestJS dengan message queue Redis.",
    testimonial_text: "Velo berhasil menjembatani kebutuhan pembayaran harian dan manajemen aset digital dengan cara yang sangat simpel.",
    testimonial_author: "CTO Velo Finance",
    media: [{ type: "image", url: "/images/ewallet_app.png" }]
  }
];

fs.writeFileSync(portfoliosStorePath, JSON.stringify(seedPortfolios, null, 2), 'utf8');
console.log('Successfully seeded local portfolios_store.json fallback data!');
